# Generated by Django 5.2.16 on 2026-08-11 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0006_requesttimeline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveBigIntegerField(help_text='مبلغ به ریال', verbose_name='مبلغ')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('failed', 'ناموفق'), ('cancelled', 'لغو شده')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت')),
                ('gateway', models.CharField(choices=[('manual', 'دستی'), ('zarinpal', 'زرین\u200cپال'), ('idpay', 'آیدی\u200cپی')], default='manual', max_length=30, verbose_name='درگاه پرداخت')),
                ('authority', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='شناسه پرداخت در درگاه')),
                ('reference_id', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='شماره مرجع')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان پرداخت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='cases.servicerequest', verbose_name='درخواست خدمت')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['service_request', 'status'], name='payment_request_status_idx')],
            },
        ),
    ]
