# Generated by Django 5.2.16 on 2026-08-18 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GatewayProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True, verbose_name='کد درگاه')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='payments/gateways/', verbose_name='لوگو')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('priority', models.PositiveIntegerField(db_index=True, default=0, verbose_name='اولویت نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'ارائه\u200cدهنده درگاه',
                'verbose_name_plural': 'ارائه\u200cدهندگان درگاه',
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True, verbose_name='کد روش پرداخت')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('icon', models.CharField(blank=True, help_text='مثلاً Bootstrap Icon', max_length=100, verbose_name='آیکون')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('priority', models.PositiveIntegerField(db_index=True, default=0, verbose_name='اولویت نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'روش پرداخت',
                'verbose_name_plural': 'روش\u200cهای پرداخت',
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='payment',
            name='authority',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='شناسه تراکنش ارائه\u200cدهنده'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='gateway',
            field=models.CharField(choices=[('manual', 'دستی'), ('zarinpal', 'زرین\u200cپال'), ('idpay', 'آیدی\u200cپی')], default='manual', max_length=30, verbose_name='درگاه پرداخت قدیمی'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='شماره مرجع تأییدشده'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('awaiting_verification', 'در انتظار تأیید'), ('paid', 'پرداخت شده'), ('failed', 'ناموفق'), ('cancelled', 'لغو شده')], db_index=True, default='pending', max_length=30, verbose_name='وضعیت'),
        ),
        migrations.CreateModel(
            name='CardToCardPaymentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer_reference', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='شماره پیگیری اعلام\u200cشده توسط کاربر')),
                ('receipt', models.FileField(blank=True, null=True, upload_to='payments/card_to_card/', verbose_name='رسید پرداخت')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان اعلام پرداخت')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان بررسی')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='دلیل رد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='card_to_card_detail', to='payments.payment', verbose_name='پرداخت')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_card_to_card_payments', to=settings.AUTH_USER_MODEL, verbose_name='بررسی\u200cشده توسط')),
            ],
            options={
                'verbose_name': 'جزئیات پرداخت کارت\u200cبه\u200cکارت',
                'verbose_name_plural': 'جزئیات پرداخت\u200cهای کارت\u200cبه\u200cکارت',
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.gatewayprovider', verbose_name='ارائه\u200cدهنده درگاه'),
        ),
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.paymentmethod', verbose_name='روش پرداخت'),
        ),
    ]
