# Generated by Django 5.2.16 on 2026-08-18 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_migrate_legacy_payment_methods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='gateway',
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.paymentmethod', verbose_name='روش پرداخت'),
        ),
    ]
