# Generated by Django 5.2.16 on 2026-08-18 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_remove_payment_gateway_alter_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardToCardDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('card_number', models.CharField(max_length=32, verbose_name='شماره کارت')),
                ('iban', models.CharField(blank=True, max_length=34, verbose_name='شماره شبا')),
                ('account_holder', models.CharField(max_length=150, verbose_name='نام صاحب حساب')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='نام بانک')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('priority', models.PositiveIntegerField(db_index=True, default=0, verbose_name='اولویت نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'کارت مقصد کارت\u200cبه\u200cکارت',
                'verbose_name_plural': 'کارت\u200cهای مقصد کارت\u200cبه\u200cکارت',
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.AddField(
            model_name='cardtocardpaymentdetail',
            name='destination_account_holder',
            field=models.CharField(blank=True, max_length=150, verbose_name='صاحب حساب در زمان پرداخت'),
        ),
        migrations.AddField(
            model_name='cardtocardpaymentdetail',
            name='destination_bank_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='بانک مقصد در زمان پرداخت'),
        ),
        migrations.AddField(
            model_name='cardtocardpaymentdetail',
            name='destination_card_number',
            field=models.CharField(blank=True, max_length=32, verbose_name='شماره کارت مقصد در زمان پرداخت'),
        ),
        migrations.AddField(
            model_name='cardtocardpaymentdetail',
            name='destination_iban',
            field=models.CharField(blank=True, max_length=34, verbose_name='شماره شبای مقصد در زمان پرداخت'),
        ),
        migrations.AddField(
            model_name='cardtocardpaymentdetail',
            name='destination_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='عنوان مقصد در زمان پرداخت'),
        ),
        migrations.AddField(
            model_name='cardtocardpaymentdetail',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_details', to='payments.cardtocarddestination', verbose_name='کارت مقصد'),
        ),
    ]
