# Generated by Django 5.2.16 on 2026-08-07 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0008_alter_servicecategory_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('submitted', 'ثبت شده'), ('under_review', 'در حال بررسی'), ('needs_correction', 'نیازمند اصلاح'), ('ready_for_payment', 'آماده پرداخت'), ('processing', 'در حال انجام'), ('completed', 'تکمیل شده'), ('cancelled', 'لغو شده'), ('rejected', 'رد شده')], default='draft', max_length=30)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='services.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
