# Generated by Django 5.2.16 on 2026-08-08 19:20

import cases.models.service_request
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
        ('services', '0008_alter_servicecategory_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicerequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'درخواست خدمت', 'verbose_name_plural': 'درخواست\u200cهای خدمات'},
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='amount',
            field=models.PositiveBigIntegerField(default=0, help_text='مبلغ به ریال', verbose_name='مبلغ'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان تکمیل'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='زمان ایجاد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='request_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='اطلاعات درخواست'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان شروع انجام'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان ثبت'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='tracking_code',
            field=models.CharField(db_index=True, default=cases.models.service_request.generate_tracking_code, editable=False, max_length=20, verbose_name='کد پیگیری'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='services.service', verbose_name='خدمت'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('submitted', 'ثبت شده'), ('under_review', 'در حال بررسی'), ('needs_correction', 'نیازمند اصلاح'), ('ready_for_payment', 'آماده پرداخت'), ('processing', 'در حال انجام'), ('completed', 'تکمیل شده'), ('cancelled', 'لغو شده'), ('rejected', 'رد شده')], db_index=True, default='draft', max_length=30, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
