# Generated by Django 5.2.16 on 2026-08-08 20:52

import cases.models.service_request
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_alter_servicerequest_options_servicerequest_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='tracking_code',
            field=models.CharField(db_index=True, default=cases.models.service_request.generate_tracking_code, editable=False, max_length=20, unique=True, verbose_name='کد پیگیری'),
        ),
    ]
