# Generated by Django 5.2.16 on 2026-08-08 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_alter_servicerequest_tracking_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=30, verbose_name='وضعیت قبلی')),
                ('to_status', models.CharField(max_length=30, verbose_name='وضعیت جدید')),
                ('note', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان تغییر')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='تغییر توسط')),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='cases.servicerequest', verbose_name='درخواست خدمت')),
            ],
            options={
                'verbose_name': 'تاریخچه وضعیت درخواست',
                'verbose_name_plural': 'تاریخچه وضعیت درخواست\u200cها',
                'ordering': ['created_at'],
            },
        ),
    ]
