# Generated by Django 5.2.16 on 2026-08-08 21:45

import cases.models.request_document
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_requeststatushistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.SlugField(max_length=100, verbose_name='شناسه فیلد')),
                ('file', models.FileField(upload_to=cases.models.request_document.request_document_upload_to, verbose_name='فایل')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='نسخه')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تأیید شده'), ('rejected', 'رد شده'), ('replaced', 'جایگزین شده')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='دلیل رد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='cases.servicerequest', verbose_name='درخواست خدمت')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_request_documents', to=settings.AUTH_USER_MODEL, verbose_name='آپلود توسط')),
            ],
            options={
                'verbose_name': 'مدرک درخواست',
                'verbose_name_plural': 'مدارک درخواست\u200cها',
                'ordering': ['field_key', '-version'],
                'constraints': [models.UniqueConstraint(fields=('service_request', 'field_key', 'version'), name='unique_request_document_version')],
            },
        ),
    ]
