# Generated by Django 5.2.16 on 2026-08-09 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_requestdocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('status_changed', 'تغییر وضعیت'), ('document_uploaded', 'بارگذاری مدرک'), ('document_approved', 'تأیید مدرک'), ('document_rejected', 'رد مدرک'), ('payment', 'پرداخت'), ('note', 'یادداشت'), ('system', 'سیستمی')], db_index=True, max_length=30, verbose_name='نوع رویداد')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='اطلاعات تکمیلی')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='زمان رویداد')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_timeline_events', to=settings.AUTH_USER_MODEL, verbose_name='انجام\u200cدهنده')),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='cases.servicerequest', verbose_name='درخواست خدمت')),
            ],
            options={
                'verbose_name': 'رویداد درخواست',
                'verbose_name_plural': 'رویدادهای درخواست\u200cها',
                'ordering': ['created_at'],
            },
        ),
    ]
