# Generated by Django 5.2.16 on 2026-08-13 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_requesttimeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('submitted', 'ثبت شده'), ('under_review', 'در حال بررسی'), ('needs_correction', 'نیازمند اصلاح'), ('ready_for_payment', 'آماده پرداخت'), ('paid', 'پرداخت شده'), ('processing', 'در حال انجام'), ('completed', 'تکمیل شده'), ('cancelled', 'لغو شده'), ('rejected', 'رد شده')], db_index=True, default='draft', max_length=30, verbose_name='وضعیت'),
        ),
    ]
