# Generated by Django 5.2.16 on 2026-08-04 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(blank=True, max_length=100, verbose_name='متن Badge')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('subtitle', models.TextField(verbose_name='زیر عنوان')),
                ('primary_button_text', models.CharField(max_length=100, verbose_name='متن دکمه اول')),
                ('primary_button_url', models.CharField(max_length=255, verbose_name='لینک دکمه اول')),
                ('secondary_button_text', models.CharField(blank=True, max_length=100, verbose_name='متن دکمه دوم')),
                ('secondary_button_url', models.CharField(blank=True, max_length=255, verbose_name='لینک دکمه دوم')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hero/', verbose_name='تصویر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'Hero',
                'verbose_name_plural': 'Hero',
                'ordering': ['sort_order'],
            },
        ),
    ]
