# Generated by Django 5.2.16 on 2026-08-04 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_herosection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='آیکون Bootstrap')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'مزیت',
                'verbose_name_plural': 'مزیت\u200cها',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('value', models.CharField(max_length=50, verbose_name='مقدار')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='آیکون Bootstrap')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'آمار',
                'verbose_name_plural': 'آمارها',
                'ordering': ['sort_order'],
            },
        ),
    ]
