# Generated by Django 5.2.16 on 2026-08-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_feature_statistic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='herosection',
            options={'ordering': ['sort_order'], 'verbose_name': 'بخش Hero', 'verbose_name_plural': 'بخش Hero'},
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='aparat',
            field=models.URLField(blank=True, verbose_name='آپارات'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='copyright',
            field=models.CharField(blank=True, max_length=255, verbose_name='متن کپی\u200cرایت'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='default_og_image',
            field=models.ImageField(blank=True, null=True, upload_to='seo/', verbose_name='تصویر پیش\u200cفرض Open Graph'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='footer_text',
            field=models.TextField(blank=True, verbose_name='متن فوتر'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='google_analytics_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Google Analytics ID'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='google_site_verification',
            field=models.CharField(blank=True, max_length=255, verbose_name='Google Search Console Verification'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='instagram',
            field=models.URLField(blank=True, verbose_name='اینستاگرام'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='linkedin',
            field=models.URLField(blank=True, verbose_name='لینکدین'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='telegram',
            field=models.URLField(blank=True, verbose_name='تلگرام'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='address',
            field=models.TextField(blank=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='فاوآیکون'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='لوگو'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='seo_description',
            field=models.TextField(blank=True, verbose_name='توضیحات سئو'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='seo_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='عنوان سئو'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='site_description',
            field=models.TextField(blank=True, verbose_name='توضیحات سایت'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='whatsapp',
            field=models.URLField(blank=True, verbose_name='لینک واتساپ'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش'),
        ),
    ]
