# Generated by Django 5.2.16 on 2026-08-06 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_alter_herosection_options_sitesetting_aparat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_title', models.CharField(default='چه خدمتی نیاز دارید؟', max_length=150, verbose_name='عنوان جستجو')),
                ('search_placeholder', models.CharField(default='نام خدمت موردنظر را جستجو کنید', max_length=255, verbose_name='متن داخل جستجو')),
                ('search_button_text', models.CharField(default='جستجو', max_length=100, verbose_name='متن دکمه جستجو')),
                ('featured_services_title', models.CharField(default='خدمات پرکاربرد', max_length=150, verbose_name='عنوان خدمات پرکاربرد')),
                ('featured_services_button_text', models.CharField(default='مشاهده همه خدمات', max_length=100, verbose_name='متن دکمه همه خدمات')),
                ('process_title', models.CharField(default='چطور کار می\u200cکند؟', max_length=150, verbose_name='عنوان مراحل انجام کار')),
                ('features_title', models.CharField(default='چرا CMAH؟', max_length=150, verbose_name='عنوان بخش مزیت\u200cها')),
                ('cta_title', models.CharField(default='همین حالا درخواست خود را ثبت کنید', max_length=200, verbose_name='عنوان دعوت به اقدام')),
                ('cta_description', models.TextField(default='خدمت موردنظر خود را انتخاب کنید و درخواستتان را آنلاین ثبت کنید.', verbose_name='توضیحات دعوت به اقدام')),
                ('cta_button_text', models.CharField(default='مشاهده خدمات', max_length=100, verbose_name='متن دکمه دعوت به اقدام')),
            ],
            options={
                'verbose_name': 'تنظیمات صفحه اصلی',
                'verbose_name_plural': 'تنظیمات صفحه اصلی',
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان مرحله')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات مرحله')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='آیکون Bootstrap')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'مرحله انجام کار',
                'verbose_name_plural': 'مراحل انجام کار',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TrustItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('icon', models.CharField(default='bi-check-circle', max_length=100, verbose_name='آیکون Bootstrap')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'نشان اعتماد',
                'verbose_name_plural': 'نشان\u200cهای اعتماد',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='feature',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'مزیت', 'verbose_name_plural': 'مزیت\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='herosection',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'بخش Hero', 'verbose_name_plural': 'بخش\u200cهای Hero'},
        ),
        migrations.AlterModelOptions(
            name='statistic',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'آمار', 'verbose_name_plural': 'آمارها'},
        ),
        migrations.AddField(
            model_name='herosection',
            name='image_alt',
            field=models.CharField(blank=True, max_length=255, verbose_name='متن جایگزین تصویر'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='icon',
            field=models.CharField(blank=True, max_length=100, verbose_name='آیکون Bootstrap'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='badge_text',
            field=models.CharField(blank=True, max_length=150, verbose_name='متن بالای عنوان'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='primary_button_text',
            field=models.CharField(max_length=100, verbose_name='متن دکمه اصلی'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='primary_button_url',
            field=models.CharField(help_text='مثال: /services/', max_length=255, verbose_name='لینک دکمه اصلی'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='secondary_button_url',
            field=models.CharField(blank=True, help_text='مثال: #how-it-works', max_length=255, verbose_name='لینک دکمه دوم'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='subtitle',
            field=models.TextField(verbose_name='توضیحات زیر عنوان'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان اصلی'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='icon',
            field=models.CharField(blank=True, max_length=100, verbose_name='آیکون Bootstrap'),
        ),
    ]
