# Generated by Django 5.2.16 on 2026-08-06 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_menu_menuitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='ترتیب نمایش'),
        ),
    ]
