# Generated by Django 5.2.16 on 2026-08-06 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_alter_menuitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='شناسه'),
        ),
    ]
