# Generated by Django 5.2.16 on 2026-08-06 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_menu_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='شناسه'),
        ),
    ]
