# Generated by Django 5.2.16 on 2026-08-06 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='is_active',
        ),
        migrations.AddField(
            model_name='page',
            name='excerpt',
            field=models.TextField(blank=True, verbose_name='خلاصه'),
        ),
        migrations.AddField(
            model_name='page',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='seo/pages/', verbose_name='تصویر Open Graph'),
        ),
        migrations.AddField(
            model_name='page',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشر شده'), ('archived', 'بایگانی')], default='draft', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AddField(
            model_name='page',
            name='template',
            field=models.CharField(choices=[('default', 'پیش فرض'), ('contact', 'تماس با ما'), ('faq', 'سوالات متداول')], default='default', max_length=50, verbose_name='قالب نمایش'),
        ),
    ]
