# Generated by Django 5.2.16 on 2026-08-06 23:56

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_remove_page_is_active_page_excerpt_page_og_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='محتوا'),
        ),
    ]
