# Generated by Django 5.2.16 on 2026-07-30 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان خدمت')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='آدرس خدمت')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='توضیح کوتاه')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('government_fee', models.PositiveIntegerField(default=0, verbose_name='هزینه دولتی')),
                ('service_fee', models.PositiveIntegerField(default=0, verbose_name='کارمزد CMAH')),
                ('cashback_percent', models.PositiveSmallIntegerField(default=0, verbose_name='درصد کش بک')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'خدمت',
                'verbose_name_plural': 'خدمات',
                'ordering': ['sort_order', 'title'],
            },
        ),
    ]
