# Generated by Django 5.2.16 on 2026-08-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_servicecategory_options_service_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='is_popular',
        ),
        migrations.RemoveField(
            model_name='service',
            name='meta_keywords',
        ),
        migrations.AddField(
            model_name='service',
            name='button_text',
            field=models.CharField(default='ثبت درخواست', max_length=100, verbose_name='متن دکمه'),
        ),
        migrations.AddField(
            model_name='service',
            name='delivery_time',
            field=models.CharField(blank=True, max_length=100, verbose_name='زمان انجام'),
        ),
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bootstrap Icon'),
        ),
        migrations.AddField(
            model_name='service',
            name='is_online',
            field=models.BooleanField(default=True, verbose_name='کاملاً آنلاین'),
        ),
        migrations.AddField(
            model_name='service',
            name='og_description',
            field=models.TextField(blank=True, verbose_name='Open Graph Description'),
        ),
        migrations.AddField(
            model_name='service',
            name='og_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Open Graph Title'),
        ),
        migrations.AddField(
            model_name='service',
            name='required_documents',
            field=models.TextField(blank=True, verbose_name='مدارک موردنیاز'),
        ),
        migrations.AddField(
            model_name='service',
            name='steps',
            field=models.TextField(blank=True, verbose_name='مراحل انجام'),
        ),
        migrations.AlterField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='service',
            name='seo_description',
            field=models.TextField(blank=True, verbose_name='SEO Description'),
        ),
        migrations.AlterField(
            model_name='service',
            name='seo_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='SEO Title'),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='service',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='icon',
            field=models.CharField(blank=True, help_text='Bootstrap Icon', max_length=100, verbose_name='آیکون'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتیب'),
        ),
    ]
