# Generated by Django 5.2.16 on 2026-08-06 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_service_og_image_alter_service_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecategory',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, unique=True, verbose_name='آدرس'),
        ),
    ]
