# Generated by Django 5.2.16 on 2026-08-09 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_servicecategory_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100, verbose_name='شناسه فیلد')),
                ('label', models.CharField(max_length=150, verbose_name='عنوان فیلد')),
                ('field_type', models.CharField(choices=[('text', 'متن'), ('textarea', 'متن چندخطی'), ('number', 'عدد'), ('date', 'تاریخ'), ('select', 'لیست انتخابی'), ('radio', 'انتخاب تکی'), ('checkbox', 'چک\u200cباکس'), ('file', 'فایل')], default='text', max_length=20, verbose_name='نوع فیلد')),
                ('required', models.BooleanField(default=False, verbose_name='الزامی')),
                ('reusable', models.BooleanField(default=False, verbose_name='قابل استفاده مجدد')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('help_text', models.CharField(blank=True, max_length=255, verbose_name='راهنما')),
                ('placeholder', models.CharField(blank=True, max_length=150, verbose_name='Placeholder')),
                ('choices', models.JSONField(blank=True, default=list, verbose_name='گزینه\u200cها')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='services.service', verbose_name='خدمت')),
            ],
            options={
                'verbose_name': 'فیلد خدمت',
                'verbose_name_plural': 'فیلدهای خدمات',
                'ordering': ['order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('service', 'key'), name='unique_service_field_key')],
            },
        ),
    ]
