# Generated by Django 5.2.16 on 2026-07-30 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='is_mobile_verified',
            field=models.BooleanField(default=False, verbose_name='تأیید شماره موبایل'),
        ),
    ]
