# Generated by Django 5.2.16 on 2026-08-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_otpcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otpcode',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='otpcode',
            index=models.Index(fields=['user', 'created_at'], name='accounts_ot_user_id_516972_idx'),
        ),
        migrations.AddIndex(
            model_name='otpcode',
            index=models.Index(fields=['expires_at'], name='accounts_ot_expires_2f08f4_idx'),
        ),
    ]
