# Generated by Django 5.2.16 on 2026-08-09 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_otpcode_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100, verbose_name='کلید')),
                ('value', models.TextField(blank=True, verbose_name='مقدار')),
                ('is_verified', models.BooleanField(db_index=True, default=False, verbose_name='تأیید شده')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تأیید')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'اطلاعات کاربر',
                'verbose_name_plural': 'اطلاعات کاربران',
                'ordering': ['key'],
                'constraints': [models.UniqueConstraint(fields=('user', 'key'), name='unique_user_attribute')],
            },
        ),
    ]
